### ISSUE TITLE
bug if source warehouse is not set

### ISSUE THREAD

**Issue by XpansaDima** [Comunitea/CMNT_25_15_GZ#1]
I created three lines in Sale Order:
5 items source warehouse = warehouse 1
10 items source warehouse = warehouse 2
15 items source warehouse is not set
warehouse 1 is default warehouse on Sale Order form

as a result transfers are created. 

5 items on warehouse 1
10 items on warehouse 2
15 items are missing

**Comment by omar7r** [comment]
Hi,

I check this issue and it works for me, two pickings the first with the first and third line and the second only with the second line. Get the last revisions, maybe now it's correct because I was migrating this project from 6.1 to 8.0 version and sale_different_warehouse module was the last migrated.

Regards
